export const menuPhotos = {
    icedLatte: require('../../assets/iced-latte.png'),
    supernova: require('../../assets/supernova.png'),
    roaringFrappe: require('../../assets/roaring-frappe.png'),
    blackWhiteColdBrew: require('../../assets/black-and-white-cold-brew.png'),
    strawberryLimeade: require('../../assets/strawberry-limeade.png'),
    shakenLemonade: require('../../assets/shaken-lemonade.png'),
    manninoCrepe: require('../../assets/mannino-crepe.png'),
    downtowner: require('../../assets/downtowner.png'),
    funkyMonkey: require('../../assets/funky-monkey.png'),
    leSmores: require('../../assets/le-smores.png'),
    strawberryFields: require('../../assets/strawberry-fields.png'),
    bonjour: require('../../assets/bonjour.png'),
    bananasFoster: require('../../assets/bananas-foster.png'),
    mattsScrambledEggs: require('../../assets/matts-scrambled-eggs.png'),
    meanieMushroom: require('../../assets/meanie-mushroom.png'),
    turkeyClub: require('../../assets/turkey-club.png'),
    greenMachine: require('../../assets/green-machine.png'),
    perfectPair: require('../../assets/perfect-pair.png'),
    crepeFromage: require('../../assets/crepe-fromage.png'),
    farmersMarketCrepe: require('../../assets/farmers-market-crepe.png'),
    travisSpecial: require('../../assets/travis-special.png'),
    cremeBrulagel: require('../../assets/creme-brulagel.png'),
    theFancyOne: require('../../assets/the-fancy-one.png'),
    breakfastBagel: require('../../assets/breakfast-bagel.png'),
    theClassic: require('../../assets/the-classic.png'),
};